### ISSUE TITLE
Sending commands

### ISSUE THREAD

**Issue by volant0098** [vondraussen/gps_tracker_gateway#6]
Hi, 
First it is better to say thanks for sharing your codes.
I want to know: can this code send command to the device too? Or just recives its data?

**Comment by vondraussen** [comment]
@volant0098 this depends on the gps tracker libs. E.g. for GT06 it [will send the response message](https://github.com/vondraussen/gps_tracker_gateway/blob/310e8ee28df9f30a95854180dfb4522e3179df1a/app.js#L139), but that is actually implemented in the [GT06 lib](https://github.com/vondraussen/gt06).
